# Generated by Django 3.2.4 on 2021-06-24 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subsidio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beneficiario',
            name='NIT',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
